FROM python:3.7

COPY requirements.txt .
RUN pip3 install -r requirements.txt

RUN mkdir /app
WORKDIR /app

COPY protos/* /app/protos
COPY *.py /app/
RUN python3 run_codegen.py

ENTRYPOINT ["python3", "client-api.py"]
