# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inference.proto',
  package='inference',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0finference.proto\x12\tinference\"3\n\x14ImageClassifierInput\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\x12\r\n\x05shape\x18\x02 \x03(\x05\"&\n\x15ImageClassifierOutput\x12\r\n\x05label\x18\x01 \x01(\t2_\n\x0fImageClassifier\x12L\n\x07Predict\x12\x1f.inference.ImageClassifierInput\x1a .inference.ImageClassifierOutputb\x06proto3'
)




_IMAGECLASSIFIERINPUT = _descriptor.Descriptor(
  name='ImageClassifierInput',
  full_name='inference.ImageClassifierInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='inference.ImageClassifierInput.data', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='shape', full_name='inference.ImageClassifierInput.shape', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=81,
)


_IMAGECLASSIFIEROUTPUT = _descriptor.Descriptor(
  name='ImageClassifierOutput',
  full_name='inference.ImageClassifierOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='inference.ImageClassifierOutput.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=121,
)

DESCRIPTOR.message_types_by_name['ImageClassifierInput'] = _IMAGECLASSIFIERINPUT
DESCRIPTOR.message_types_by_name['ImageClassifierOutput'] = _IMAGECLASSIFIEROUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ImageClassifierInput = _reflection.GeneratedProtocolMessageType('ImageClassifierInput', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECLASSIFIERINPUT,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.ImageClassifierInput)
  })
_sym_db.RegisterMessage(ImageClassifierInput)

ImageClassifierOutput = _reflection.GeneratedProtocolMessageType('ImageClassifierOutput', (_message.Message,), {
  'DESCRIPTOR' : _IMAGECLASSIFIEROUTPUT,
  '__module__' : 'inference_pb2'
  # @@protoc_insertion_point(class_scope:inference.ImageClassifierOutput)
  })
_sym_db.RegisterMessage(ImageClassifierOutput)



_IMAGECLASSIFIER = _descriptor.ServiceDescriptor(
  name='ImageClassifier',
  full_name='inference.ImageClassifier',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=123,
  serialized_end=218,
  methods=[
  _descriptor.MethodDescriptor(
    name='Predict',
    full_name='inference.ImageClassifier.Predict',
    index=0,
    containing_service=None,
    input_type=_IMAGECLASSIFIERINPUT,
    output_type=_IMAGECLASSIFIEROUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGECLASSIFIER)

DESCRIPTOR.services_by_name['ImageClassifier'] = _IMAGECLASSIFIER

# @@protoc_insertion_point(module_scope)
