apiVersion: v1
kind: Service
metadata:
  name: vgg16-inference-api-port
  labels:
    service-name: vgg16-inference-api
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 80
      nodePort: 30030
      protocol: TCP
  selector:
    service-name: vgg16-inference-api
